### ISSUE TITLE
AR Filing - UX recommendation for wording - Due date: August 13

### ISSUE THREAD

**Issue by sarahelz19** [bcgov/business-ar#293]
AR Filing - Please review and provide UX enhanced template 
@janisrogers
https://docs.google.com/document/d/1944k_HAL4d-Ql_CCTft26Q6aMMcfQAwSQyNABGnvV1E/edit
 

Based on current feedback from UX 

UX please provide an enhanced AR reminder for use in the next cohort - by Friday August 9th 
Next cohort delivery is scheduled for Monday August 12th.

**Comment by magszymanski** [comment]
100% of the people did not file in the Business Registry. OCM reached out to all 23 filers for a quick 5 minute call to find out why. Three responses:

### One thanked for the reminder, didn’t read the content, went to COLIN, filed there (didn’t read)

- Was good to get the reminder to remember to file. 
- Went online (COLIN) and followed instructions that were given on the website
- “I didn’t pay attention to the email”

### One followed instructions, went to click on nanoID, link invalid (technical)
- Followed the link, said to register with a BC Services Card. downloaded it, went back to the link, and it was invalid
- Went back to the app and couldn’t find the AR filing in the BCSC app (told him it only acts as an identity validator, not a two way-street)
- Was very very frustrated “I was feeling like a really old man”
- Let it go, went online a week later and found somewhere were it said he can still do it the old way, “said thank god, will try it again next year”
- Very glad you called me

### One found the process confusing and recommended we don’t make changes (resistance)
Really don’t want to schedule a call, however I found it very confusing. I believe I had to try and register on some special platform. I was having issues, so I called and someone sent me a link like we used to get before this new one and it worked great and caused me no confusion. I recommend you don’t change, or make it easy so we don’t have to re-register. You have all the info already, so why can’t it just be transported to this new system instead of us trying to figure it out. We are a very small business and I”m 74 years old, so need it as simple as possible. 

**Considerations:**
Validate nano IDs
Consider changing subject line to reflect it’s a new way to file to capture attention
Context (why the change), WIIFM

**Comment by Maribeth-Wilson** [comment]
@hanlunBCRegistries @ozamani9gh - are you also able to update the GC Notify template? Please advise.

@thorwolpert - fyi

**Comment by ozamani9gh** [comment]
@hanlunBCRegistries the template lives in the code base here:

https://github.com/bcgov/business-ar/blob/main/jobs/ar-reminder/src/ar_reminder/email_templates/ar_reminder.html
