### ISSUE TITLE
INVESTIGATE - Fix differences in effective date and or time

### ISSUE THREAD

**Issue by Maribeth-Wilson** [bcgov/business-ar#307]
- There is a difference in effective dates. This could cause implications – users submitting in BCROS, not COLIN, there is a difference in time (2 minutes) in ledger vs actual filing time (please let me know if you need more info) - Elizabeth has confirmed that there could be possible implications of this and could result in additional phone calls to Joshua’s unit.  

<img width="952" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelNLQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--662e44aaf533c48ab2e82776cf4c5139a5751856/image.png" alt="image.png" />

- This one, issue with date and time – filed in BCROS on Aug 20 at 8:57pm but reflecting in COLIN as August 21 at 8:00am. It was also filed before the anniversary date.  
<img width="975" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBem1LQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--079288cf7408863a4d558c2d2b308783324ed3e1/image.png" alt="image.png" />

**Comment by Maribeth-Wilson** [comment]
@nsmenon8890 - fyi

**Comment by EPortman** [comment]
Each filing gets 3 dates:
1. Date and time when AR is submitted (before paying)  ----> `Filing Date`
2. Date and time when AR is paid (successful payment)  ----> `Payment Completion Date`
3. Date and time when AR is processed (AR completion) ----> `Completion Date`

It seems the issue here was that there was a delay between `Payment Completion Date` and `Completion Date`  due to the time needed to sync with Colin. 

I changed it so that these two dates and times are identical.  I kept the filing date as is as that doesn't seem to be a problem? This can easily be changed so that all three are the same though. I tested it with this business and the times are now in sync. 
<img width="1340" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGFxQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9798379cf9a381e010ac371a9884dc10132380ec/image.png" alt="image.png" />



Before these changes the data in the database looked like this (notice the time delay between `completion date` and `payment_completion_date`:
<img width="1320" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGlxQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4e43bf805f425fc55af58f45c57bad084ebf1410/image.png" alt="image.png" />

**Comment by Maribeth-Wilson** [comment]
@nsmenon8890 - FYI

**Comment by EPortman** [comment]
This one is quite tricky. 

I updated the data in Google Cloud so that all of the data fields are consistent when an AR is filed. Here is an example below.
<img width="1506" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGV2Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7c9c7be30e279aa2227eab4b2d2659326c2f68ed/image.png" alt="image.png" />

Even with the data being consistent on the Business AR side of things, Colin still displays the `effective date` to be something different - usually a couple of minutes in the future, but sometimes as much as an entire day. 
<img width="1539" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHF2Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5063a075fa5a30fd76dab1498c04fa2f83b83425/image.png" alt="image.png" />

It seems as if something is happening to the effective date in the post request that gets sent to Lear  which is located here.

https://github.com/bcgov/lear/blob/f045c27b19792ea63e9596cf2313148f6432063f/colin-api/src/colin_api/resources/filing.py#L90-L93

Further work needs to be done on this issue, specifically finding out why Lear is changing the effective date.

**Comment by ozamani9gh** [comment]
We believe the issue is in COLIN_API in lear:

<img width="1134" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1N2Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--44d9b2ee52239c220b15c265147345b2787c2e78/image.png" alt="image.png" />

**Comment by EPortman** [comment]
It seems like the problem with this one is how Colin is displaying the effective date and date fields. 

In Business AR, a filing is sent to the Colin API that looks like this;
```
2024-09-13 11:12:00,479 - process_paid_filings.job - INFO in job:job.py:99 - send_filing: Filing details to be sent:
2024-09-13 11:12:00,480 - process_paid_filings.job - INFO in job:job.py:100 - send_filing: {
    "filing": {
        "annualReport": {
            "annualGeneralMeetingDate": "2024-09-12",
            "annualReportDate": "2010-09-26",
            "unanimousResolutionDate": "",
            "votedForNoAGM": false
        },
        "business": {
            "adminFreeze": "False",
            "corpState": "ACT",
            "corpStateClass": "ACT",
            "email": "",
            "foundingDate": "2008-09-26T05:07:54-00:00",
            "goodStanding": false,
            "hasFutureEffectiveFilings": false,
            "homeCompanyName": "",
            "homeJurisdictionNumber": "",
            "homeRecognitionDate": "",
            "identifier": "0835905",
            "jurisdiction": "BC",
            "lastAgmDate": "2024-09-11",
            "lastArDate": "2009-09-26",
            "lastLedgerTimestamp": "2024-09-12T19:26:32-00:00",
            "legalName": "LAMA PASS FUEL CO. LTD.",
            "legalType": "BC",
            "nextARYear": 2010,
            "status": "Active",
            "taxId": "123"
        },
        "documents": [
            {
                "name": "Receipt",
                "url": "https://business-ar-api-dev-dy4loprnwa-nn.a.run.app/v1/business/0835905/filings/142/documents/receipt"
            }
        ],
        "header": {
            "certifiedBy": "",
            "certifiedByDisplayName": "",
            "colinIds": [],
            "completionDate": "",
            "date": "2024-09-13T18:10:36.984605+00:00",
            "filingDateTime": "2024-09-13T18:10:36.984605+00:00",
            "filingYear": 2010,
            "id": 142,
            "name": "annualReport",
            "paymentAccount": "3495",
            "paymentStatus": "COMPLETED",
            "paymentToken": 40656,
            "status": "PAID",
            "submitter": "",
            "learEffectiveDate": "2024-09-13T18:10:36.984605+00:00",
            "source": "BAR"
        }
    }
}
```

In the above example, both date and affective date are the exact same. The result for this filing in Colin ends up looking like this:
<img width="1356" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXpaQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1fb2bb8b8d5ce7fe024c6edef90ac595e9b1fa16/image.png" alt="image.png" />

Date and time filed is 5 minutes in the future. After looking and playing around with the endpoint in Lear it seems this date and time filed field is coming from elsewhere - changing it has no effect on what is displayed in Colin. This date and time filed field seems to be coming from the event table which has the date defined as SYSDATE. Therefore when a record is added the date and time filed is always different because it is using the time of the transaction which wiill always be different than the time stamp in Business AR before sending the data over.

**Comment by EPortman** [comment]
In the above example, the date and time filed was at 11:15. This is coming from CDEV from the field event_timestamp. 
<img width="1609" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0xaQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1c24a9e1bbf740ff8305fd09dcccf53da2c8389f/image.png" alt="image.png" />

@ozamani9gh what do you think?

**Comment by ozamani9gh** [comment]
@Maribeth-Wilson This needs to go to home team to fix.  I can't tag Michael Kagis.  can you send this to home team, and CC Thayne.

"Date and time filed is 5 minutes in the future. After looking and playing around with the endpoint in Lear it seems this date and time filed field is coming from elsewhere - changing it has no effect on what is displayed in Colin. This date and time filed field seems to be coming from the event table which has the date defined as SYSDATE. Therefore when a record is added the date and time filed is always different because it is using the time of the transaction which wiill always be different than the time stamp in Business AR before sending the data over."
