### ISSUE TITLE
AR Reminder support required - fixing build errors in test & dev environs

### ISSUE THREAD

**Issue by Maribeth-Wilson** [bcgov/business-ar#309]
Fixing Build Errors in Test and Dev Environments: 

Issue: The build for the AR-reminder job fails in the test and dev environments but succeeds in prod. 

Action: Figure out the root cause of the build failure in these environments.

**Comment by Maribeth-Wilson** [comment]
@hanlunBCRegistries, @ozamani9gh - fyi

**Comment by ozamani9gh** [comment]
@ozamani9gh break this down to all the issues we have in dev and test.

**Comment by Maribeth-Wilson** [comment]
@ozamani9gh - has this issue been resolved?

**Comment by hanlunBCRegistries** [comment]
@ozamani9gh @Maribeth-Wilson We are building the CI/CD workflow for ar-reminder job since this job doesn't have a github action for it so we cannot implement any changes against it. Once the CI/CD workflow is implemented we should be able to implement all our changes through github actions instead of having Thor clone our code and push the changes.

**Comment by Maribeth-Wilson** [comment]
To confirm @hanlunBCRegistries - does this mean you and Omid will be able to work on the outstanding tickets, including the ones that are currently assigned to Thor?
