### ISSUE TITLE
Confirm AR Reminder batch job will automatically update COLIN and turn off AR Prompt

### ISSUE THREAD

**Issue by Maribeth-Wilson** [bcgov/business-ar#314]
The modern AR Prompt batch job needs to implement the following:
insert into set_ar_to_no (CORP_NUM,PREVIOUS_VALUE,UPDATE_DATE) values (:corp_num,(select send_ar_ind from corporation where corp_num=:corp_num),sysdate)
update corporation set send_ar_ind='N' where corp_num=:corp_num

@thorwolpert - please confirm this will be in place for the Sep 3 release (see tix [288](https://app.zenhub.com/workspaces/annual-report-filing-for-corporations-661483a4f4f833001637ec44/issues/gh/bcgov/business-ar/288) for more context

**Comment by droberts27** [comment]
Maybe the AR Prompt batch job was not run CDEV and CTST and the manual process did not involve updating corporation.send_ar_ind to 'N'.

**Comment by EPortman** [comment]
The AR reminder batch job currently does not update Colin. 

Probably the best way for this to be implemented is to create an endpoint in LEAR for Business AR to call during the AR Reminder Batch Job. 

This endpoint would need to do two things (by being passed the corp num):
1. Insert the corporation into the `set_ar_to_no` table
2. Updates the `send_ar_ind` field in the `corporation` table from `y` to `n` for the corporation

@ozamani9gh would you be okay with asking Entities team to implement this endpoint so that we can call it from Business AR?

**Comment by JazzarKarim** [comment]
Hi, can you please tag it to release "Entities Release 22.6b"? Thanks! @ozamani9gh @EPortman
