### ISSUE TITLE
Investigation:   Error filing annual report - please investigate and resolve

### ISSUE THREAD

**Issue by Maribeth-Wilson** [bcgov/business-ar#380]
Please see below links:
[BC registries error 1.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2dVQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b558b157e21a8b2ef518873d13a9d05d799c75e3/BC%20registries%20error%201.pdf)
[BC registries error.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2tVQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7e7037af46cf83d34dd41877d2d200e474f0a938/BC%20registries%20error.pdf)
<img width="978" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN29VQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--79f5d5583fc31c8b81843a1df4a1a3e34402d151/image.png" alt="image.png" />

**Comment by nsmenon8890** [comment]
Hi Omid,

Could you please look into this issue? Let me know if you need any further information so that I can coordinate with the respective team to provide the necessary details.

**Comment by hanlunBCRegistries** [comment]
<img width="1370" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVphQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ed60d9dca7f8d9c038d5057beab16084b243be9/image.png" alt="image.png" />
<img width="1011" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWRhQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--72ea20150db62b25bbc1d74bc8265882325fb920/image.png" alt="image.png" />
<img width="1982" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXBhQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f5c264fba55a2ea9acb3301950c3f22c8d676a83/image.png" alt="image.png" />
Looks like the user filed thru Colin already, but there are 2 filing records, I am checking with David Roberts regarding the two filings since there filing type is different:<img width="1261" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGRiQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--923e4504e99b464c4ba6460593313219eae927f0/image.png" alt="image.png" />
<img width="1296" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGhiQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e6de37b532362639e08fb0cd1016a6f06c5cba2a/image.png" alt="image.png" />

**Comment by hanlunBCRegistries** [comment]
According to David Roberts, NOCDR is Notice of Change of Directors and ANNBC is BC Annual Report, so the client has filed in Colin.

**Comment by ozamani9gh** [comment]
@Maribeth-Wilson  we will close this ticket since user went to colin to file
