### ISSUE TITLE
Where should the 'Home' links lead to

### ISSUE THREAD

**Issue by deetz99** [bcgov/business-ar#83]
Do we allow a user to navigate back to the home page of the Annual Report site mid-flow?

What is the expected behaviour of selecting the 'Service BC Connect' link in the header?
What is the expected behaviour of selecting the 'Home' link in the footer?

Currently these both point to the home page of the Annual Report site, which causes a redirect to the 'Authorization Required' page, since there is no nanoid in the url.

Should we allow users to navigate back to the home page? Or should the 'home' links point back to the Registry site?

I could make the 'Service BC Connect' in the header be text only and remove the link and then the 'Home' in the footer can point to the Registry site.

I don't see the purpose of allowing a user to go back to the home page of the Annual Report site (given the structured flow of this app) as then I would have to save the current business nanoid, which would immediately either show the 'completed' state or redirect the user to the Annual Report form if the filing wasn't completed.

**Comment by trishreimer** [comment]
Do we allow a user to navigate back to the home page of the Annual Report site mid-flow? **No, for mvp, suggesting no links out mid-flow.** 
What is the expected behaviour of selecting the 'Service BC Connect' link in the header? **Do not enable the link in the header please.**
What is the expected behaviour of selecting the 'Home' link in the footer? **User can navigate to [www.bcregistry.gov.bc.ca](http://www.bcregistry.gov.bc.ca/). Suggest new window. This page does not require authorization.**
Currently these both point to the home page of the Annual Report site, which causes a redirect to the 'Authorization Required' page, since there is no nanoid in the url.
Should we allow users to navigate back to the home page? Or should the 'home' links point back to the Registry site? Only home. **See above.**
I could make the 'Service BC Connect' in the header be text only and remove the link and then the 'Home' in the footer can point to the Registry site. **see above**.
I don't see the purpose of allowing a user to go back to the home page of the Annual Report site (given the structured flow of this app) as then I would have to save the current business nanoid, which would immediately either show the 'completed' state or redirect the user to the Annual Report form if the filing wasn't completed. **Agreed. What happens if they click their ‘back’ button in the browser mid-flow?**

**Comment by deetz99** [comment]
@trishreimer 

I will update the links accordingly.

As for using the back button in the browser, its less using the back button and more-so what happens when navigating to a new page (manually typing in a new url will cause the same behaviour), it depends on the filing/auth state. 

The **home page** will either show the filing is completed, redirect to the AR page if theres a filing in progress or redirect to the choose account screen if theres no filing in progress. 

The **account pages** will redirect you to the AR page if you already have a filing in progress. 

I will need to add something for the AR + final page depending on the filing state. 

Every page except for home and missing-id page will redirect back to home if theres no logged in user.
